server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: Andya@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

logging: 
  pattern: 
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]" 
management.tracing.sampling.probability: 1.0
